config:
  target: 'http://localhost:6002'
  phases:
    - duration: 10
      arrivalRate: 1000
      name: "1000 RPS"
  payload:
    path: "ids.csv"
    fields:
      - "id"
scenarios:
  - name: "Load nearby transit options"
    flow:
      - get:
          url: "/api/getNearbyTransitOptions/{{ id }}"
